// TODO: Manually writing this out for now.
// Will eventually be autogenerated and can be imported from `hooks`...

import { gql, useQuery } from '@apollo/client';

const QUERY_SERVICE_PROVIDER_LOOKUP = gql`
  query ServiceProviderLookup($input: EmailProviderIsGoogleRequestDto!) {
    providerFromAddress(input: $input) {
      emailAddress
      isGoogle
    }
  }
`;

type $TODO = any;

export const useServiceProviderLookup = (input: $TODO) => {
  const { data, loading, error } = useQuery<$TODO>(
    QUERY_SERVICE_PROVIDER_LOOKUP,
    {
      variables: { input },
      skip: !input,
    },
  );

  return {
    loading: loading,
    error,
    result: data?.providerFromAddress,
  };
};
